// import axios from "axios";
export const GET_DOGS = "GET_DOGS";
export const GET_NAME_DOG = "GET_NAME_DOG";
export const GET_TEMPERAMENT = "GET_TEMPERAMENT";
export const FILTER_BY_TEMPERAMENTS = "FILTER_BY_TEMPERAMENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
// export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
export const GET_DETAILS = "GET_DETAILS";
export const CREATE_DOG = "CREATE_DOG";
